classDiagram

    direction LR

    namespace JavaFX {
        
        class Node {
            <<abstract>>
        }

        class ImageView {
            +x: double
            +y: double
            +fitWidth: double
            +fitHeight: double
            +preserveRatio: boolean
            +smooth: boolean
        }

        class MediaView {
            +x: double
            +y: double
            +fitWidth: double
            +fitHeight: double
            +preserveRatio: boolean
            +smooth: boolean
        }

        class Canvas {
            +width: double
            +height: double
        }

        class GraphicsContext {
            +fill() void
            +stroke() void
            +clip() void
        }

        class Image {
            +width: double
            +height: double
        }

        class MediaPlayer {
            +rate: double
            +volume: double
            +currentTime: double
            +play() void
            +pause() void
            +stop() void
        }

        class Media {
            +width: double
            +height: double
            +duration: double
        }

        class SubScene {
            +width: double
            +height: double
        }

        class Shape {
            <<abstract>>
            +strokeWidth: double
            +smooth: boolean
        }

        class Shape3D {
            <<abstract>>
            +cullFace: CullFace
            +drawMode: DrawMode
        }

        class Camera {
            <<abstract>>
            +nearClip: double
            +farClip: double
        }

        class Paint {
            <<abstract>>
        }

        class Material {
            <<abstract>>
        }

        class LightBase {
            <<abstract>>
            +lightOn: boolean
        }

        class Color {
            
        }

    }

    Node <|-- ImageView

    Node <|-- MediaView

    Node <|-- Canvas

    Canvas o-->"1" GraphicsContext

    ImageView o-->"1" Image

    MediaView o-->"1" MediaPlayer

    MediaPlayer o-->"1" Media
    
    Node <|-- Shape

    Shape o-->"2" Paint: stroke / fill

    SubScene o-->"1" Camera: camera
    SubScene o-->"1" Paint: fill

    Node <|-- Camera

    Node "1"<--o SubScene: root
    Node <|-- SubScene

    Node <|-- Shape3D

    Shape3D o-->"1" Material

    Node <|-- LightBase

    LightBase o-->"1" Color

    Color --|> Paint

    style Node fill:white
    style Paint fill:white
    style Color fill:white
    style Material fill:white