classDiagram

    direction LR

    namespace JavaFX {
        
        class Node {
            <<abstract>>
        }

        class ImageView {
            +x: double
            +y: double
            +fitWidth: double
            +fitHeight: double
            +preserveRatio: boolean
            +smooth: boolean
        }

        class MediaView {
            +x: double
            +y: double
            +fitWidth: double
            +fitHeight: double
            +preserveRatio: boolean
            +smooth: boolean
        }

        class Canvas {
            +width: double
            +height: double
        }

        class GraphicsContext {
            +fill() void
            +stroke() void
            +clip() void
        }

        class Image {
            +width: double
            +height: double
        }

        class MediaPlayer {
            +rate: double
            +volume: double
            +currentTime: double
            +play() void
            +pause() void
            +stop() void
        }

        class Media {
            +width: double
            +height: double
            +duration: double
        }

        class SubScene {
            +...
        }

        class Shape {
            <<abstract>>
            +strokeWidth: double
            +smooth: boolean
        }

        class Shape3D {
            <<abstract>>
            +...
        }

        class Camera {
            <<abstract>>
            +...
        }

        class Paint {
            <<abstract>>
        }

        class Material {
            <<abstract>>
        }

    }

    Node <|-- ImageView

    Node <|-- MediaView

    Node <|-- Canvas

    Node <|-- SubScene
    
    Node <|-- Shape

    Node <|-- Shape3D

    Node <|-- Camera

    Canvas o-->"1" GraphicsContext

    ImageView o-->"1" Image

    MediaView o-->"1" MediaPlayer

    MediaPlayer o-->"1" Media

    Shape o-->"1" Paint: stroke
    Shape o-->"1" Paint: fill

    Shape3D o-->"1" Material

    style Node fill:white
    style Paint fill:white
    style Material fill:white