classDiagram

    namespace JavaFX {

        class Stage {
        }
        class Scene {
        }
        class Node {
            <<abstract>>
        }
        class Parent {
            <<abstract>>
        }
        class Group {
        }
        class Region {
            <<abstract>>
        }
        class Control {
            <<abstract>>
        }
        class Pane {
            <<abstract>>
        }
        class Chart {
            <<abstract>>
        }
        class PieChart {
        }
        class XYChart {
        }
        class GridPane {
        }
        class BorderPane {
        }
        class FlowPane {
        }
        class StackPane {
        }
        class ScrollPane {
        }
        class SplitPane {
        }
        class TabPane {
        }
        class Tab {
        }
        class ListView {
        }
        class TableView {
        }
        class TreeView {
        }
        class TreeTableView {
        }
        class Canvas {
        }
        class GraphicsContext {
        }
        class ImageView {
        }
        class MediaView {
        }
        class WebView {
        }
        class WebEngine {
        }
        class MenuBar {
        }
        class ToolBar {
        }
        class ButtonBar {
        }
        class Labeled {
            <<abstract>>
        }
        class Label {
        }
        class ButtonBase {
            <<abstract>>
        }
        class Button {
        }
        class Hyperlink {
        }
        class CheckBox {
        }
        class ToggleButton {
        }
        class RadioButton {
        }
        class MenuButton {
        }
        class SplitMenuButton {
        }
        class Image {
        }
        class MediaPlayer {
        }
        class Media {
        }
        class ChoiceBox {
        }
        class ProgressIndictor {
        }
        class Spinner {
        }
        class Slider {
        }

    }

    Stage o-->"1" Scene

    Scene o-->"1" Parent

    Node <|-- Parent
    Node "*"<--o Parent: children
    Node <|-- Canvas
    Node <|-- ImageView
    Node <|-- MediaView

    Canvas o-->"1" GraphicsContext

    ImageView o-->"1" Image

    MediaView o-->"1" MediaPlayer

    MediaPlayer o-->"1" Media

    Parent <|-- WebView
    Parent <|-- Group
    Parent <|-- Region

    WebView o-->"1" WebEngine

    Region <|-- Pane
    Region <|-- Control
    Region <|-- Chart

    Pane <|-- BorderPane
    Pane <|-- GridPane
    Pane <|-- StackPane
    Pane <|-- FlowPane

    Control <|-- Labeled
    Control <|-- Spinner
    Control <|-- Slider
    Control <|-- ChoiceBox
    Control <|-- ProgressIndictor
    Control <|-- MenuBar
    Control <|-- ToolBar
    Control <|-- ButtonBar
    Control <|-- ScrollPane
    Control <|-- SplitPane
    Control <|-- TabPane
    Control <|-- ListView
    Control <|-- TableView
    Control <|-- TreeView
    Control <|-- TreeTableView

    Labeled <|-- Label
    Labeled <|-- ButtonBase

    ButtonBase <|-- Button
    ButtonBase <|-- MenuButton
    ButtonBase <|-- ToggleButton
    ButtonBase <|-- Hyperlink
    ButtonBase <|-- CheckBox

    MenuButton <|-- SplitMenuButton

    ToggleButton <|-- RadioButton

    TabPane o-->"*" Tab

    Chart <|-- PieChart
    Chart <|-- XYChart