classDiagram

    namespace JavaFX {

        class Region {
            
        }

        class Pane {

        }

        class Control {
            <<abstract>>
        }

        class ContextMenu {
            +hide() void
        }

        class MenuItem {
            +visible: boolean
            +disable: boolean
            +text: String
            +style: String
        }

        class Menu {
            +showing: boolean
            +show() void
        }

        class CheckMenuItem {
            +selected: boolean
        }

        class RadioMenuItem {
            +selected: boolean
        }

        class ToggleGroup {

        }

        class Toggle {
            <<interface>>
        }

        class Tooltip {
            +activated: boolean
            +text: String
            +textAlignment: TextAlignment
            +textOverrun: OverrunStyle
            +wrapText: boolean
        }

        class Font {

        }

    }

    Region <|-- Pane
    Region <|-- Control

    Control o-->"1" ContextMenu
    Control o-->"1" Tooltip

    ContextMenu o-->"*" MenuItem

    MenuItem <|-- RadioMenuItem
    MenuItem <|-- CheckMenuItem
    MenuItem "*"<--o Menu: items
    MenuItem <|-- Menu

    ToggleGroup o-->"*" Toggle
    ToggleGroup ..> Toggle: selectedToggle

    Toggle <|-- RadioMenuItem

    Tooltip ..> Font

    style Region fill:white
    style Font fill:white