classDiagram

    direction LR

    namespace Lang {

        class System {
            <<static>>
        }

    }

    namespace IO {

        class OutputStream {
            <<abstract>>
            +write(c: int) void
            +flush() void
            +close() void
        }

        class FileOutputStream {
            +FileOutputStream(name: string)
        }

        class IOException {

        }

        class FileNotFoundException {

        }
        
    }

    System o..>"1" OutputStream: out

    OutputStream <|-- FileOutputStream
    OutputStream ..> IOException: throws

    FileOutputStream ..> FileNotFoundException: throws

    IOException <|-- FileNotFoundException

    style System fill:white