classDiagram

    direction LR

    namespace Lang {

        class System {
            <<static>>
        }

    }

    namespace IO {

        class InputStream {
            <<abstract>>
            +read() int
            +close() void
        }

        class Reader {
            <<abstract>>
            +read() int
            +close() void
        }

        class BufferedReader {
            +BufferedReader(r: Reader, size: int)
            +readLine() String
        }

        class InputStreamReader {
            +InputStreamReader(s: InputStream)
        }

        class FileReader {
            +FileReader(name: String)
        }
        
    }

    System o-->"1" InputStream: in

    Reader <|-- BufferedReader

    Reader "1"<.. BufferedReader: reader

    Reader <|-- InputStreamReader

    Reader <|-- FileReader

    InputStreamReader ..>"1" InputStream: stream

    style System fill:white
    style InputStream fill:white