classDiagram

    direction LR

    namespace Lang {

        class System {
            <<static>>
        }

    }

    namespace IO {

        class InputStream {
            <<abstract>>
            +read() int
            +close() void
        }

        class Reader {
            <<abstract>>
            +read() int
            +close() void
        }

        class BufferedReader {
            +BufferedReader(r: Reader, size: int)
            +readLine() String
        }

        class InputStreamReader {
            +InputStreamReader(s: InputStream)
            +InputStreamReader(s: InputStream, c: Charset)
            +InputStreamReader(s: InputStream, d: CharsetDecoder)
        }

        class FileReader {
            +FileReader(name: String)
        }

        class Charset {
            <<abstract>>
            +encode(str: String) ByteBuffer
            +encode(cb: CharBuffer) ByteBuffer
            +decode(bb: ByteBuffer) CharBuffer
        }
        
    }

    System o-->"1" InputStream: in

    Reader <|-- BufferedReader

    Reader "1"<.. BufferedReader: reader

    Reader <|-- InputStreamReader

    InputStreamReader ..>"1" Charset: charset

    InputStreamReader <|-- FileReader

    InputStreamReader ..>"1" InputStream: stream

    style System fill:white
    style InputStream fill:white