classDiagram

    direction LR

    namespace Lang {

        class System {
            <<static>>
        }

    }

    namespace IO {

        class OutputStream {
            <<abstract>>
            +write(c: int)
            +flush() void
            +close() void
        }

        class Writer {
            <<abstract>>
            +write(str: String) void
            +flush() void
            +close() void
        }

        class OutputStreamWriter {
            +OutputStreamWriter(o: OutputStream)
            +OutputStreamWriter(o: OutputStream, c: Charset)
        }

        class PrintWriter {
            +print(b: boolean) void
            +print(c: char) void
            +print(i: int) void
            +print(l: long) void
            +print(f: float) void
            +print(d: double) void
            +print(s: String) void
            +print(o: Object) void
        }

        class FileWriter {
            +FileWriter(name: String)
        }

        class Charset {
            <<abstract>>
            +encode(str: String) ByteBuffer
            +encode(cb: CharBuffer) ByteBuffer
            +decode(bb: ByteBuffer) CharBuffer
        }
        
    }

    System o-->"1" PrintWriter: out

    Writer <|-- PrintWriter
    Writer "0..1"<.. PrintWriter: writer

    PrintWriter ..>"1" OutputStream: stream

    Writer <|-- OutputStreamWriter

    OutputStreamWriter ..>"1" OutputStream: stream
    OutputStreamWriter <|-- FileWriter

    OutputStreamWriter ..>"1" Charset: charset

    style System fill:white
    style OutputStream fill:white