classDiagram

    direction LR

    namespace Lang {

        class System {
            <<static>>
        }

    }

    namespace IO {

        class OutputStream {
            <<abstract>>
            +write(c: int)
            +flush() void
            +close() void
        }

        class Writer {
            <<abstract>>
            +write(str: String) void
            +flush() void
            +close() void
        }

        class PrintWriter {
            +print(s: String) void
            +println(s: String) void
        }

        class FileWriter {
            +FileWriter(name: String)
        }
        
    }

    System o-->"1" PrintWriter: out

    Writer <|-- PrintWriter
    Writer "0..1"<.. PrintWriter: writer

    PrintWriter ..>"0..1" OutputStream: stream

    Writer <|-- FileWriter

    style System fill:white
    style OutputStream fill:white