classDiagram

    namespace JavaFX {

        class Control {
            <<abstract>>
        }

        class ProgressIndicator {

        }

        class ProgressBar {

        }

    }

    Control <|-- ProgressIndicator

    ProgressIndicator <|-- ProgressBar

    style Control fill:white