classDiagram

    direction LR

    namespace JavaFX {

        class Control {
            <<abstract>>
        }

        class ListView["ListView&lt;T&gt;"] {
        }

        class TableView["TableView&lt;T&gt;"] {
        }

        class TreeView["TreeView&lt;T&gt;"] {
        }

        class TreeTableView["TreeTableView&lt;T&gt;"] {
        }

    }

    Control <|-- ListView
    Control <|-- TableView
    Control <|-- TreeView
    Control <|-- TreeTableView

    style Node fill:white
    style Control fill:white