classDiagram

    direction LR

    namespace JavaFX {

        class LightBase {
            <<abstract>>
        }

        class AmbientLight {

        }

        class PointLight {

        }

    }

    LightBase <|-- AmbientLight
    LightBase <|-- PointLight

    style LightBase fill:white