classDiagram

    direction LR

    namespace JavaFX {

        class Shape3D {
            <<abstract>>
        }

        class Box {
            +width: double
            +height: double
            +depth: double
        }

        class Sphere {
            +radius: double
            +divisions: int
        }

        class Cylinder {
            +height: double
            +radius: double
            +divisions: int
        }

        class MeshView {

        }

        class Mesh {
            <<abstract>>
        }

    }

    Shape3D <|-- Box
    Shape3D <|-- Sphere
    Shape3D <|-- Cylinder
    Shape3D <|-- MeshView

    MeshView o-->"1" Mesh: mesh

    style Shape3D fill:white
    style Mesh fill:white